name: Basic CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Install dev tools
        run: |
          rustup update
          rustup component add clippy
          rustup component add rustfmt
          cargo install cargo-udeps

      - name: Build
        run: cargo build

      - name: Test
        run: ROCKET_DATABASES='{books_db={url="books.db"}}' cargo test -- --test-threads=1

      - name: Lint
        run: |
          cargo clippy -- -D warnings
          cargo fmt -- --check
          cargo +nightly udeps

      - name: Test if program starts
        run: |
          ROCKET_DATABASES='{books_db={url="books.db"}}' cargo run &
          sleep 5
          [[ `jobs | wc -l` -gt 0 ]]
