name: Basic CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

      - name: Test if program starts
        run: |
          cargo run &
          sleep 5
          ps aux | grep cargo
