name: Basic CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Install dev dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Test if program starts
        run: |
          ROCKET_DATABASES='{books_db={url="books.db"}}' cargo run &
          sleep 5
          [[ `jobs | wc -l` -gt 0 ]]
