name: Basic CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
      
      - name: Install dev dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev 

      - name: Build
        run: cargo build

      - name: Test if program starts
        run: |
          cargo run &
          sleep 5
          export LINES_IN_PS_AUX=`ps aux | grep cargo | wc -l`
          [[ $LINES_IN_PS_AUX -gt 1 ]]
